.android_before_script: &android_before_script
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - chmod +x ./gradlew

generate-android-apk:
  image: jangrewe/gitlab-ci-android
  <<: *android_before_script
  script: |
    apt-get update
    apt-get -y install jq
    curl -O https://gist.githubusercontent.com/geigi/caad0773f1e7d798de9e1ecf6e00df2d/raw/5d3049746bd72b8adeed904f7864d68738147277/get-last-successful-build-artifact.sh
    chmod +x get-last-successful-build-artifact.sh
    ./get-last-successful-build-artifact.sh
    ls -ahl
    unzip artifacts.zip
    rm -rf Mods/*/Linux
    rm -rf Mods/*/OSX
    rm -rf Mods/*/Windows
    cp -R Mods app/src/main/assets/
    ./gradlew assembleRelease
    ls -ahl
    find . -name '*.apk'
  # retry because sometimes checkingout artifacts fails
  retry: 2
  artifacts:
    paths:
    - ./app/build/outputs/apk/release/*.apk
    expire_in: 1 week
  variables:
    BUILD_TARGET: Android
    BASE_URL: https://git.it-sec.medien.hs-duesseldorf.de
    PROJECT: 76
    STAGE: build
    JOB_NAME: build-android